version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    target-branch: 'development'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 20

  - package-ecosystem: 'npm'
    directory: '/site'
    schedule:
      interval: 'daily'
    target-branch: 'development'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 20
